### ISSUE TITLE
Engine config without installer

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout-engine#115]
I had been using the installer and replacing the engine but I would like to try just running the engine from command line.  I get though the install with [INSTALL.md](https://github.com/ffplayout/ffplayout_engine/blob/master/docs/INSTALL.md) but I am not familiar with systemd.  
says to:
"change user and group in service file (for example to www-data)"
?
Where/ what is this?

/etc/systemd/system/ ffplayout_engine.service   ?

change User=root to User=username?  
I am on Ubuntu 21.10  ...I read “default the configuration of the owner is www-data in the Ubuntu configuration”

What and how do I configure?

Thanks!

**Comment by jb-alvarado** [comment]
If you run the engine only manually from command line, you don't need the systemd service. The service takes care, the the engine start always on system boot, or after a crash.

If you want to use the service, normally yo don't want to run that process as root user, you want reduce the permission of the program, so it does nothing bad on your system. When system has the system user and group **www-data** the this is a good user to choice. You can check **/etc/passwd**, if that user exists.

I use that user, because normally web services use this one, and we want to modify the config over the frontend.

**Comment by tvadi** [comment]
Ok, So I have the engine/api/frontend installed from the installer, playlist made and saved.   Trying:
`./ffplayout.py -l none -p ~/playlist.json -d -s now -t none -o stream`
error: unrecognized arguments: -d -o stream, try...
`./ffplayout.py -l none -p ~/playlist.json -s now -t none
[2022-03-10 13:58:55,519][ERROR]    ffmpeg contains no zmq filter!  Text messages will not work...
Traceback (most recent call last):
  File "/opt/ffplayout_engine/./ffplayout.py", line 67, in <module>
    main()
  File "/opt/ffplayout_engine/./ffplayout.py", line 60, in main
    output = import_module(f'ffplayout.output.{mode}').output
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/ffplayout_engine/ffplayout/output/stream.py", line 26, in <module>
    from ..folder import GetSourceFromFolder, MediaStore, MediaWatcher
  File "/opt/ffplayout_engine/ffplayout/folder.py", line 27, in <module>
    from watchdog.events import PatternMatchingEventHandler
ModuleNotFoundError: No module named 'watchdog'`

**Comment by jb-alvarado** [comment]
When your config is correct, and you have your playlists in the path you set in the config, you can start with:

```
./ffplayout.py -l none
```
But you error shows that you have not all python modules installed. Are you using the virtual environment and have you source it, before running the engine?

**Comment by tvadi** [comment]
Running on a dedicated i5 Ubuntu 21.10.  Sorry, source what?

**Comment by jb-alvarado** [comment]
When you have created a virtual environment, let's say in **venv**, than you have to run `source venv/bin/active` and then install the python packages with `pip`. And in this "sourced environment" you also have to run your command.

**Comment by jb-alvarado** [comment]
I close here, because I switched to Rust, and there is the installation more easy.
