### ISSUE TITLE
Testing buffer tools

### ISSUE THREAD

**Issue by jb-alvarado** [ffplayout/ffplayout-engine#13]
The buffer tools needs to be testet. I think they create different time shifts. Over 24 hours pipebuffer for example create a shift from ~15 seconds.

**Comment by Angel54689** [comment]
I am open for the test. What do you need exactly?

**Comment by jb-alvarado** [comment]
Ah, don't worry :). Is more a reminder for me - I want to figure out witch buffer tool have the smallest latency. I just need to do some runs over 24 hours with every tool.

**Comment by jb-alvarado** [comment]
With mbuffer the time shift is only ~8 seconds... Now I test pv.

**Comment by jb-alvarado** [comment]
Test is done... Result is [here](https://github.com/ffplayout/ffplayout-engine/wiki/The-Buffer)

**Comment by jb-alvarado** [comment]
I need to restart this tests, and also apologize. I think the big shifts was coming from **-shortest** parameter which I had use. Filter apad and -shortest is useless for ffplayout, I can say now.

**Comment by jb-alvarado** [comment]
Now I have only 1 second shift over 24 hours with mbuffer...

**Comment by jb-alvarado** [comment]
Now final conclusion is, that there is NO difference between the buffer tools. The shift was coming from **-shortest** parameter...
