### ISSUE TITLE
Issue while changing clips

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#15]
Hi there, 

Few questions here: 

- What should be the buffer and buffer size for 1280 x 720 and 1920 x 1080 
- When changing config to 1280 x 720 my both CPU cores max out? Any reason? I can see I have 80-90% used having running default configuration.   
- I keep getting this error when changing clips, it actually doesn't skip to next MP4 and I ger

`    Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p, 1024x576 [SAR 1:1 DAR 16:9], q=-1--1, 25 fps, 1k tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 1300000/0/0 buffer size: 2600000 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp (24 bit), 128 kb/s
    Metadata:
      encoder         : Lavc57.107.100 aac
[flv @ 0x55ff97cdb6c0] Failed to update header with correct duration.
[flv @ 0x55ff97cdb6c0] Failed to update header with correct filesize.
frame= 4892 fps= 25 q=-1.0 Lsize=   23741kB time=00:03:15.60 bitrate= 994.3kbits/s speed=0.998x
video:20412kB audio:3093kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.003540%
[libx264 @ 0x55ff97cdc640] frame I:138   Avg QP:18.25  size: 22685
[libx264 @ 0x55ff97cdc640] frame P:1395  Avg QP:21.21  size:  7370
[libx264 @ 0x55ff97cdc640] frame B:3359  Avg QP:23.55  size:  2230
[libx264 @ 0x55ff97cdc640] consecutive B-frames:  6.6%  4.0%  4.9% 84.5%
[libx264 @ 0x55ff97cdc640] mb I  I16..4: 50.7%  0.0% 49.3%
[libx264 @ 0x55ff97cdc640] mb P  I16..4: 19.3%  0.0%  5.1%  P16..4: 32.6% 10.8%  4.1%  0.0%  0.0%    skip:28.1%
[libx264 @ 0x55ff97cdc640] mb B  I16..4:  1.6%  0.0%  0.3%  B16..8: 30.8%  3.7%  0.4%  direct: 2.6%  skip:60.6%  L0:46.2% L1:50.4% BI: 3.3%
[libx264 @ 0x55ff97cdc640] coded y,uvDC,uvAC intra: 23.6% 56.5% 11.5% inter: 4.3% 17.2% 0.4%
[libx264 @ 0x55ff97cdc640] i16 v,h,dc,p: 44% 29%  9% 19%
[libx264 @ 0x55ff97cdc640] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 23% 22%  4%  4%  5%  4%  4%  3%
[libx264 @ 0x55ff97cdc640] i8c dc,h,v,p: 46% 23% 23%  8%
[libx264 @ 0x55ff97cdc640] Weighted P-Frames: Y:0.4% UV:0.2%
[libx264 @ 0x55ff97cdc640] ref P L0: 68.5%  6.8% 18.9%  5.8%  0.0%
[libx264 @ 0x55ff97cdc640] ref B L0: 90.7%  7.8%  1.5%
[libx264 @ 0x55ff97cdc640] ref B L1: 96.7%  3.3%
[libx264 @ 0x55ff97cdc640] kb/s:854.49`

![image](https://user-images.githubusercontent.com/36647913/58380902-64e14500-7faf-11e9-843c-f97afaea623b.png)

Thanks for script

**Comment by maddigibiter** [comment]
Update on my side, should have checked first. Playlist generator adds only one file to playlist when I use 
`./gen_playlist_from_subfolders.sh /home/ubuntu/media/*.mp4`
but if I run
`./gen_playlist_from_subfolders.sh /home/ubuntu/media/` 
it generates the full playlist. 

It would be great to have your input with regards to buffer adjustments as when I increase resolution it lags even when I adjust buffer size and its tolerance. 

Thanks

**Comment by maddigibiter** [comment]
Further testing this is what I get when increasing resolution and can see lags in video

![image](https://user-images.githubusercontent.com/36647913/58384032-fb742d00-7fd4-11e9-8f38-61c5478546d6.png)

Br

**Comment by jb-alvarado** [comment]
Hi @maddigibiter,
forget about the buffer setting, this ones have nothing to do with your lags. The buffer only take care that the ffmpeg output instance get an continues input stream.  See [here](https://github.com/ffplayout/ffplayout-engine/wiki/The-Buffer).
Maybe I should not expose this settings to the user :)...

I think your problem have to do with your system specs. For HD to get a good quality you need a bigger pre processing bitrate, maybe around 150000. And you need to tweak your output compression settings under **[OUT]**.

There you need a higher maxrate and bufsize. And at the begin you say you have 2 cores? That is not much for HD streaming. Try a different preset, maybe veryfast or higher, for more information you can look [here](https://trac.ffmpeg.org/wiki/Encode/H.264).

**Comment by maddigibiter** [comment]
Hi @jb-alvarado , 

Yes 2 cores, I agree, it may not be the best so I upgrade it first thing tonight and will let you know. I agree, maybe buffer should remain hidden so it saves you keep repeating yourself :) 

Just to confirm, do you mean here? 
post_comp_video = ["-c:v", "libx264", "-crf", "23", "-g", "50", "-maxrate", "1300k", "-bufsize", "2600k", "-preset", "medium", "-profile:v", "Main", "-level", "3.1", "-refs", "3"]

if I change buffer size to 150k what should I update max rate to? 75K? I'll change the preset profile too and will let you know about outcome. 

I should say, I love your script. Very well done. 

Thanks

**Comment by jb-alvarado** [comment]
Yes I mean that settings. My recommendations for HD are:

- If your files has 25FPS use a gop size (-g) of 50, when you have 24FPS use 48 - so always the double...
- for **maxrate** you could try **6000k**, and a **bufsize** of **8000k**
- preset you can start with **faster**, and when your system load is to high go to a higher level
- under **[PRE_COMPRESS]** I would change the **v_bitrate** to **150000**

Thank for the compliment, I'm happy when is useful!

**Comment by maddigibiter** [comment]
Hi @jb-alvarado, tested it and ended up with veryfast, it works absolutely fine with 4 cores, each core consumption is about 40-50% now. Thank you. 

Only other question I had is, when I exist console/logout from shell, buffer stops and it doesn't stream anymore. Is there anyway to run it in background regardless of my console is active or not? 

Thanks

**Comment by maddigibiter** [comment]
I think I have my answer why stream doesn't start using 

sudo systemctl enable ffplayout && sudo systemctl start ffplayout

![image](https://user-images.githubusercontent.com/36647913/58439822-3c03a180-80ce-11e9-80a3-e48885f4c520.png)

However no idea why it failed in first place.

**Comment by jb-alvarado** [comment]
When you use ffplayout as a systemd service, all settings must be correct, also the paths to the log file, the right user in service file and the right privilege. You can check the service with systemctl status ffplayout, maybe it says you what is happen. And `systemctl enable ffplayout` you only have to run once, but when you change the service file you have to run `systemctl daemon-reload`

Running fflplayout in background could also be done by screen.

**Comment by jb-alvarado** [comment]
Just another information: when you generate your playlist with `gen_playlist_from_subfolders.sh` I think is not so good to work with systemd. Using ffplayout as a service is more for 24/7 streaming, but when you generate your playlist with the example shell script it not create a 24 hours long playlist. It just take all clips in your folder and put them in a json file.

**Comment by maddigibiter** [comment]
Sorry I've been away, thanks for information and now I know what my issue was. I didn't have correct permission set on /var/log/ffplayout so it was throwing errors all over the place. I ran 

`sudo chown -R ubuntu:ubuntu /var/log/ffplayout` and restarted daemon. Working just fine. 

Thank you, closing this issue.
