### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#16]
Hi @jb-alvarado ,

This is a feature request that I think it can add so much value to this repo. 

Description: 

Ability to support multiple subtitle for on-demand videos. This should be limited to videos hosted and not live streams ingested throughout third parties. 

Subtitles shouldn't necessarily be included in PRE-COMP but ability to reference subtitles in JSON file and requested using HTML5 Player when a video begins or is already streaming. I think this is the best approach to avoid any backend overhead and could support more than one language. 

Ideally another JSON output could handle this event, by just outputting what is being streamed. 

Any thoughts?

**Comment by jb-alvarado** [comment]
Hello @maddigibiter,
I don't know if I understand you right, but I think this is not exactly an task for ffplayout. You want something like [text-tracks](https://docs.videojs.com/docs/guides/text-tracks.html)? This should be realize in HTML/JS. Of course you can add any key/value pare in the json playlist you want, ffplayout will just ignore them and then read the values with your web app.

Beside this there is a plan for text overlay in output, but I have not started with that jet.

**Comment by maddigibiter** [comment]
Yes, text tracks, but that needs to be initiated when new video starts streaming so player can understand state of ffplayout and request correct text-track/subtitle

**Comment by jb-alvarado** [comment]
I have not read so much about text-tracks, but when I search for "dynamic text-track" I get some results. And with php/js you can read the json playlist and calculate your correct time and get the text file.

**Comment by maddigibiter** [comment]
Yeah that's what I'm thinking. I play around with it and if I come across anything useful I share. 

Thanks
