### ISSUE TITLE
Unexpected behaviour on HLS multi variant

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#19]
Hi again :) 

At this stage I'm trying to have HLS variant setup on same server I'm streaming RTMP from. After spending some time I realized that when I setup HLS variants as per as instructions on HLS RTMP Module documentation and restart nginx, FFPlayout-engine crashes and not working any more. 

Have you experience this before? I have one service worker on Nginx and 8 cores CPU with 64GB ram. Is there any way we can have multi stream from FFPlayout to Nginx? Or is there anyway to resolve this? 

I've also checked syslog, nginx logs, ffmpeg logs, ffmpeg-playout logs and I can't see any errors. If I reverse nginx configuration to serve one HLS (so there is no need to encode using FFMPEG) everything runs fine.

Thanks

**Comment by jb-alvarado** [comment]
> Hi again :)
> 
> At this stage I'm trying to have HLS variant setup on same server I'm streaming RTMP from. After spending some time I realized that when I setup HLS variants as per as instructions on HLS RTMP Module documentation and restart nginx, FFPlayout-engine crashes and not working any more.

That is a  normal behavior, when ffplayout streams to a server, and the server (nginx) stops, ffplayout loss the connection and stops also. That would be happen to, with an normal ffmpeg instance. When you use a systemd service for ffplayout it should restart immediately. 

> Have you experience this before? I have one service worker on Nginx and 8 cores CPU with 64GB ram. Is there any way we can have multi stream from FFPlayout to Nginx? Or is there anyway to resolve this?

Normally you setup your hls server one time and you don't touch it anymore, so the problem should not come up anymore. Yes you can use as much outputs from ffplayout you want, you only have to modify the output command in confing. But I would not recommend this. All this things you can do with nginx. 
We don't use nginx, we use srs, but there are very similar and there we do the same too.

**Comment by jb-alvarado** [comment]
You also could try to run both services in different VMs, or containers.

**Comment by maddigibiter** [comment]
Thanks for reply, point one understood and it makes sense however when after changes, FFMPEG fails to start I can see in systemctl status and logs that it restarts every 5 seconds but it actually never runs anymore and it fails. Below is my nginx.conf and there is nothing alien about it. I've also just tried it, restarted nginx, FFPlayout was down, enabled it and it refused to run, rebooted machine and enabled it again but still fails. I agree this is the best practice to do it within nginx so I'm trying to see if there is something wrong i do or find an alternative. I understand this is not the scope of this repo and I appreciate your support.

`
rtmp {
    server {
            listen 1935;
	   application src {
		live on;
		exec ffmpeg -i rtmp://127.0.0.1/live/stream/$name
	        -c:a libfdk_aac -b:a 32k  -c:v libx264 -b:v 128K -f flv rtmp://localhost/hls/$name_low
              	-c:a libfdk_aac -b:a 64k  -c:v libx264 -b:v 256k -f flv rtmp://localhost/hls/$name_mid
              	-c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 512K -f flv rtmp://localhost/hls/$name_hi 2> /tmp/ffmpeglog;
	
	   }
            application hls {
                    live on;
		   # pull rtmp://127.0.0.1/live/stream;
      
		    hls on;
                    hls_path /home/ubuntu/hls;
		    hls_nested on;
                    #hls_fragment 3;
            	    #hls_playlist_length 60;
		    hls_variant _low BANDWIDTH=160000;
            	    hls_variant _mid BANDWIDTH=320000;
            	    hls_variant _hi  BANDWIDTH=640000;   

            }
    }

}`

**Comment by jb-alvarado** [comment]
My knowledge for nginx/rtmp is very limited. I would guess that nginx is not listening on port 1935, or the endpoint is not correct, and that is why ffplayout fails to start. Have you check the error.log from nginx? Also an `netstat -tulpn` could help to see if nginx list listening on 1935.

**Comment by maddigibiter** [comment]
Yeah nothing in error.log, also I created a bash file to run ffmpeg from there but no joy, this is an example of my bash

`ffmpeg -i rtmp://127.0.0.1/live/stream
               -c:a libfdk_aac -b:a 32k  -c:v libx264 -b:v 128K -f flv rtmp://localhost/hls/stream_low
               -c:a libfdk_aac -b:a 64k  -c:v libx264 -b:v 256k -f flv rtmp://localhost/hls/stream_mid
               -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 512K -f flv rtmp://localhost/hls/stream_hi 2> /home/ubuntu/log/ffmpeglog;`

in ffmpeglog I get bad input/output error and nothing else. 

I think temporarily I need to do it from ffplayout.conf file until I find a solution. Would you help me with clarifying this change in ffplayout.conf? Lets assume I have two outputs would this setting work? 

Fir high resolution

`post_comp_video = [
    "-c:v", "libx264", "-crf", "23", "-x264-params", "keyint=50:min-keyint=25:scenecut=-1",
    "-maxrate", "1300k", "-bufsize", "2600k", "-preset", "medium", "-profile:v", "Main",
    "-level", "3.1"
    ]
post_comp_audio = ["-c:a", "libfdk_aac", "-ar", "44100", "-b:a", "128k"]
post_comp_extra = ["-flags", "+global_header", "-f", "flv"]
post_comp_copy = ["-bsf:a", "aac_adtstoasc"]
out_addr = rtmp://127.0.0.1/live/stream/high`

and for low

`post_comp_video = [
    "-c:v", "libx264", "-crf", "23", "-x264-params", "keyint=50:min-keyint=25:scenecut=-1",
    "-maxrate", "1300k", "-bufsize", "2600k", "-preset", "medium", "-profile:v", "Main",
    "-level", "3.1"
    ]
post_comp_audio = ["-c:a", "libfdk_aac", "-ar", "44100", "-b:a", "128k"]
post_comp_extra = ["-flags", "+global_header", "-f", "flv"]
post_comp_copy = ["-bsf:a", "aac_adtstoasc"]
out_addr = rtmp://127.0.0.1/live/stream/low`

so couple of questions: 

1- For low stream I need to cut the bufsize and screen size, what would be appropriate for mobile to implement in low example in above?

2- Would FFplayout actually stream both? You mentioned its not recommended but possible

3- Can port 1935 work with both rtmp output urls? Isn't it going to conflict as port is already in use?

**Comment by jb-alvarado** [comment]
To 1 and 2, you could try something like:

```
post_comp_video = [ "-c:v", "libx264", "-crf", "23", "-x264-params", "keyint=50:min-keyint=25:scenecut=-1", "-maxrate", "650k", "-bufsize", "1300k", "-preset", "medium", "-profile:v", "Main", "-level", "3.1", "-s", "512x288", "-c:a", "libfdk_aac", "-ar", "44100", "-b:a", "128k", "-flags", "+global_header", "-f", "flv", "rtmp://127.0.0.1/live/stream/low", "-maxrate", "1300k", "-bufsize", "2600k", "-preset", "medium", "-profile:v", "Main", "-level", "3.1"]
post_comp_audio = ["-c:a", "libfdk_aac", "-ar", "44100", "-b:a", "128k"]
post_comp_extra = ["-flags", "+global_header", "-f", "flv"]
out_addr = rtmp://127.0.0.1/live/stream/high
```
To 3, you have to try this, I think it should work, because it have different end points, but I have not test it.

**Comment by jb-alvarado** [comment]
Maybe I have your mistake.

Try your ffplayout output to: `rtmp://127.0.0.1/live/stream`

and your nginx config like:

```
application live {
    live on;
    exec ffmpeg -i rtmp://127.0.0.1/live/$name
    -c:a libfdk_aac -b:a 32k -c:v libx264 -b:v 128k -f flv rtmp://localhost/liveout/$name_low
    -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 256k -f flv rtmp://localhost/liveout/$name_mid
    -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 512k -f flv rtmp://localhost/liveout/$name_hi;
}

application liveout {
    live on;
    hls on;
    hls_path /home/ubuntu/hls/;
    hls_fragment 6s;
    hls_playlist_length 60s;
    hls_variant _low BANDWIDTH=160000;
    hls_variant _mid BANDWIDTH=320000;
    hls_variant _hi BANDWIDTH=640000;
}
```

**Comment by maddigibiter** [comment]
Tried this FFPlayout still failing.

**Comment by maddigibiter** [comment]
The other options failed too. Here is my config

```
post_comp_video = [ "-c:v", "libx264", "-crf", "23", "-x264-params", "keyint=50:min-keyint=25:scenecut=-1", 
"-maxrate", "650k", "-bufsize", "1300k", "-preset", "medium", "-profile:v", "Main", "-level", "3.1", 
"-s", "512x288", "-c:a", "aac", "-ar", "44100", "-b:a", "128k", "-flags", "+global_header", "-f", "flv", "rtmp://127.0.0.1/live/stream/low", 
"-maxrate", "6000k", "-bufsize", "8000k", "-preset", "veryfast", "-profile:v", "Main", "-level", "3.1"]
post_comp_audio = ["-c:a", "aac", "-ar", "44100", "-b:a", "128k"]
post_comp_extra = ["-flags", "+global_header", "-f", "flv"]
post_comp_copy = ["-bsf:a", "aac_adtstoasc"]
out_addr = rtmp://127.0.0.1/live/stream/high
```

**Comment by jb-alvarado** [comment]
Maybe your need to change the end `/stream/high` to `/high` and the same with low output to.

Sorry I don't know how to help you here. I think it is better that you try to find help with nginx, maybe on stackoverflow and when this works and ffplayout still run into errors then you come again here. 

And test nginx with ffmpeg not ffplayout, you add only an layer of complications.

**Comment by maddigibiter** [comment]
Hi, no, you've been amazing. I agree this is more issue with Nginx setup than FFPlayout engine. You've been so responsive and supportive and that is not scope of this repo or github so I appreciate your time and support. 

I'll play around today and ping you later. We can close this ticket if you agree.

Thanks
