### ISSUE TITLE
Can Playlist be hosted on a remote server?

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#22]
Hi, can playlist be hosted on a remote server and accessed over HTTP?

Thanks

**Comment by lavvy** [comment]
i was just thinking about this today.

**Comment by jb-alvarado** [comment]
I think this would make things more complicate then bring benefit. One good thing from ffplayout is, that almost always you can edit the playlist. And this feature is more important for me, then playlist over http. You could run also rsync/wget/curl, or you make an ssh mount.

**Comment by jb-alvarado** [comment]
In dev branch I have now a version which support this. Please test it, and give me feedback.

**Comment by lavvy** [comment]
Oh beautiful , will test it

**Comment by jb-alvarado** [comment]
In my test environment it hangs, when it should reload the playlist. I need to figure out whats happen there...

**Comment by maddigibiter** [comment]
Same here, on a ubuntu 18 it actually runs for i,e, 18 hours then it fails, if I restart its fine.

**Comment by jb-alvarado** [comment]
yesterday I fix a parameter, have you get that fix to? Because now my test runs smooth.

**Comment by lavvy** [comment]
Sounds so good it got fixed. I have been very very busy recently.

**Comment by jb-alvarado** [comment]
I only want to point out, that when you use remote playlists, it will not be possible to manage both with the WebGUI, playlists and the engine.

**Comment by maddigibiter** [comment]
of course, it makes sense. thanks

**Comment by jb-alvarado** [comment]
I close here. You can reopen it, if something is not working.
