### ISSUE TITLE
TCP port 1935 error

### ISSUE THREAD

**Issue by maddigibiter** [ffplayout/ffplayout-engine#25]
Hi, just a question

When streaming using ffplayout, is SRS or Nginx-RTMP neccessary to get ffplayout playing? Main reason I'm asking this is that when I use this command with a valid json file in order to test ffplayout status:

python3 ffplayout.py -l ~/ffplayout.log -f ~/playlist.json

I get this

![image](https://user-images.githubusercontent.com/36647913/62612651-b8e99d80-b8ff-11e9-982a-ad1271bd5d85.png)

My port is open in Firewall and disabling firewall doesn't make any changes. 
![image](https://user-images.githubusercontent.com/36647913/62612622-a8d1be00-b8ff-11e9-8aaf-cf2e92cb04b0.png)

This is third time I'm installing ffplayout-engine however this is new to me. Have in mind I don't have nginx-rtmp or SRS installed but from what I remember it doesn't need either to stream, correct? 

FFMPEG is not bundled with FFServer, I don't think we use FFserver hence I don't have any configurations. 

I'm installing SRS on docker ubuntu 19 but regardless when I google this error, all talking about ffserver. Does port 1935 has to listen? Can't we just stream rtmp? 

Thanks

**Comment by maddigibiter** [comment]
Issue resolved after digging deeper I had to allow 1935/tcp. 

For those who may have same issue on ubuntu 

`sudo ufw allow 1935/tcp `

**Comment by maddigibiter** [comment]
Not, it didn't do the trick. 1935 is open in my iptables but still saying connection refused, can I ask what OS you use in dev? FFMPEG connection is refused, even though its listed in iptables.

**Comment by jb-alvarado** [comment]
Hi, at the moment I'm not at my home, so I only can give a short answer.

It depend on what you want to do. Maybe you found here some answers: https://trac.ffmpeg.org/wiki/StreamingGuide
In general yes for rtmp you need a server and ffmpeg is normally the publisher. So you need something like nginx with rtmp, or srs. 
In your first screenshot I saw that ffplayout tried to connect to localhost for this you need to have a server listening on localhost to. 

For developing I mostly use mac, sometimes windows and when it comes to testing I use debian in two VMs . One for ffplayout and one for srs. But both can also run in one environment. Personal I don't like docker so much, so I have not much knowledge about it. I only know you have to forword the ports to the container. 
Anyway ffplayout and also srs don't messup the system, so you could run both on your machine directly. At least for testing.

**Comment by maddigibiter** [comment]
Sure, thanks - if installed successfully I may write a wiki
