### ISSUE TITLE
Restart Playout and it start from first video in playlist instead of start with current time playlist video 

### ISSUE THREAD

**Issue by darshanvithani** [ffplayout/ffplayout-engine#26]
As in Past playout, it was when i restart playout video and it restarting with the current time in video 

now after the update, it is when restarting playout and it starts the first video in playout. instead of current time video with skip time that already gone

**Comment by jb-alvarado** [comment]
Have you the lastes version from master? Can you show me one of your playlists (the source path I don't need, but the rest)? And also your config settings.

**Comment by darshanvithani** [comment]
`[GENERAL]
stop_on_error = True
stop_threshold = 11


# send error messages to email address, like:
# missing playlist
# unvalid json format
# missing clip path
# leave recipient blank, if you don't need this
# mail_level can be: WARNING, ERROR
[MAIL]
subject = "Playout Error"
smpt_server = mail.example.org
smpt_port = 587
sender_addr = ffplayout@example.org
sender_pass = 12345
recipient =
mail_level = ERROR


# Logging to file
# if log_to_file = False > log to stderr (console)
# path to /var/log/ only if you run this program as deamon
# log_level can be: DEBUG, INFO, WARNING, ERROR
[LOGGING]
log_to_file = True
log_file = /var/log/ffplayout/ffplayout.log
log_level = INFO


# output settings for the pre-compression
# all clips get prepared in that way,
# so the input for the final compression is unique
# logo is only used if the path exist
# with logo_filter = overlay=W-w-12:12 you can modify the logo position
# live_protocols is for checking input, is input a live source ffplayout handles it a bit different
[PRE_COMPRESS]
width = 1920
height = 1080
fps = 30
v_bitrate = 50000
logo = /etc/ffplayout/watermark.png
logo_filter = overlay=W-w-50:H-h-50
live_protocols = ["http", "https", "ftp", "rtmp", "rtmpe", "rtmps", "rtp", "rtsp", "srt", "tcp", "udp"]
copy_mode = False
ffmpeg_copy_settings = ["-c", "copy", "-bsf:v", "h264_mp4toannexb", "-f", "mpegts", "-"]


# playlist settings
# set playlist_mode to False if you want to play clips from the [STORAGE] section

# put only the root path here, for example: "/playlists"
# subfolders are readed by the script
# subfolders needs this structur:
# "/playlists/2018/01" (/playlists/year/month)

# day_start means at which time the playlist should start
# leave day_start blank when playlist should always start at the begin
[PLAYLIST]
playlist_mode = True
path = /playlists
day_start = 05:59:25.000


# play ordered or ramdomly files from path
# extensions: search only files with this extension, can be a list
# set shuffle to True to pick files randomly
# filler_path are for the GUI only at the moment
# filler_clip is for fill the end to reach 24 hours, it will loop when is necessary
# blackclip is for stream copy mode,
# best for this is a ~4 hours clip with black color and soft noise sound
[STORAGE]
path = /media
filler_path = /media/filler/filler-clips
filler_clip = /media/filler/filler.mp4
blackclip = /media/dummy.mp4
extensions = ["*.mp4"]
shuffle = False


# overlay text
# for paramters check ffmpeg doc
# leave textfile blank when you don't need this
# in some systems decimal point is a comma, have this in mind when ffmpeg complains about wrong values
# on windows fontfile path need to be like this: C\:/WINDOWS/fonts/DejaVuSans.ttf
# textfile has the same pattern
[TEXT]
textfile = /media/live.txt
fontsize = 24
fontcolor = black
fontfile = /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
box = 1
boxcolor = white@0xbb
boxborderw = 3
x = w-w/8*mod(t,8*(w+tw)/w)
y = (h-line_h)*0.9


# the final playout post compression
# set the settings to your needs
# preview works only on a desktop system with ffplay!! Set it to True, if you need it
[OUT]
preview = False
service_name = Live Stream
service_provider = example.org
post_comp_video = [
    "-c:v", "libx264", "-crf", "10", "-x264-params", "keyint=50:min-keyint=25:scenecut=-1",
    "-maxrate", "3000K", "-bufsize", "4000K", "-g", "60", "-preset", "medium", "-profile:v", "Main",
    "-level", "4.0"
    ]
post_comp_audio = ["-c:a", "aac", "-ar", "44100", "-b:a", "128k"]
post_comp_extra = ["-flags", "+global_header", "-f", "flv"]
post_comp_copy = ["-bsf:a", "aac_adtstoasc"]
out_addr = `

**Comment by darshanvithani** [comment]
> https://pastebin.com/raw/vYThqucX

here is url of config 

>https://pastebin.com/raw/ikAEgi9e

here is py file

**Comment by jb-alvarado** [comment]
I see that you have `playlist_mode = False`. That means that playlist is not in use at all. ffplayout only scans for videos in `/media` and plays them. In this mode, it will always starts from the begin. But if you want to use playlists you have to set `playlist_mode = True`.

There is also a newer version in the repo, some things also in config has changed.

**Comment by darshanvithani** [comment]
I already try that. let me check again

**Comment by darshanvithani** [comment]
here is screenshot >https://d.pr/i/l1K2hT

**Comment by jb-alvarado** [comment]
The error message before says that the playlist is only ~4 hours long, but your day_start is 05:59:25.000. The playlist must have 24 hours, or your day_start should be adjust.

**Comment by darshanvithani** [comment]
her is latest : https://pastebin.com/raw/ktS07mJu config file

**Comment by darshanvithani** [comment]
here is screen shot : https://d.pr/i/GSL2eg

**Comment by jb-alvarado** [comment]
Somehow day_start at 00:00:00 is not working. Can you add or subtract some seconds?

**Comment by darshanvithani** [comment]
How i add ? i do nothing .. just if i back to old code and then it work

**Comment by jb-alvarado** [comment]
Just try for example `day_start = 01:00:00.000` in config file. I try to fix that soon.

**Comment by jb-alvarado** [comment]
Should be fixed in 9fae5d4

**Comment by darshanvithani** [comment]
It work with day start `day_start = 01:00:00.000`

**Comment by jb-alvarado** [comment]
Ok fine, than it should work now also with the new fix in master.

**Comment by darshanvithani** [comment]
HI, look like still problem there 

i see there is play the last video repeated instead of play with the current time

**Comment by jb-alvarado** [comment]
I still have to fix some part, but I also think that maybe your playlist is to short.

**Comment by darshanvithani** [comment]
I have to make a 24-hour schedule and test with `day_start = 01:00:00.000` it works fine and not work `day_start = 00:00:00.000` with your latest commit

**Comment by jb-alvarado** [comment]
I have push a new commit.

**Comment by darshanvithani** [comment]
> I have push a new commit.

https://d.pr/i/wblMGh

**Comment by darshanvithani** [comment]
> > I have push a new commit.
> 
> https://d.pr/i/wblMGh

work fine if again pur 01:00:00

**Comment by jb-alvarado** [comment]
Interesting. I have to check this again.

**Comment by jb-alvarado** [comment]
Hm, this I can not reproduce. Maybe the GUI calculate something wrong?

**Comment by darshanvithani** [comment]
no gui is fine ... beacuse its work in old verion or start with 01:00:00

**Comment by jb-alvarado** [comment]
I need a bit time for that. But tell me please which commit version was working so I can compare the code.

**Comment by darshanvithani** [comment]
send me email i send you both files that work

**Comment by jb-alvarado** [comment]
There where some old staff in the gui, whats not compatible with the new engine. This I have try to fix. I also needed to update the engine config. Please try both. 

In general the GUI is a bit outdated and I will rewrite it in the future. So for now I will not put to much effort in the old version.

**Comment by darshanvithani** [comment]
NO its not GUI problem and GUI is correct with new modification and need 
so chek that its work fine now 

but have another issue .. i open issue of that
