### ISSUE TITLE
Existing video is complete and another video start

### ISSUE THREAD

**Issue by darshanvithani** [ffplayout/ffplayout-engine#27]
in between existing video is complete and another video start.  it has an issue of a black screen for 20 to 30 sec and stream stop and starts

**Comment by jb-alvarado** [comment]
Can you post output from log and from `journalctl -u ffplayout`?

**Comment by darshanvithani** [comment]
> Can you post output from log and from `journalctl -u ffplayout`?
https://pastebin.com/raw/FATe0ua1

**Comment by jb-alvarado** [comment]
I also need the ffplayout.log at least the parts where is restarts. Your system is fast enough for realtime hd?

**Comment by darshanvithani** [comment]
> I also need the ffplayout.log at least the parts where is restarts. Your system is fast enough for realtime hd?

Yes its full HD and setup in 16GB Ram and Xeon Process Dedicated Server

here is log : https://pastebin.com/raw/913Tpidn

**Comment by darshanvithani** [comment]
its stuck like this and then stream stop and start it 
https://d.pr/v/YwnES1

**Comment by jb-alvarado** [comment]
Ok, I see that some how the durations from the clips are not correct. You only generate the playlist with ffplayout gui? Are you change the framerate?, or have all clips 30 fps?

**Comment by darshanvithani** [comment]
it generates from playout GUI and all have 30fps

**Comment by jb-alvarado** [comment]
For a fast fix you could set `stop_on_error = False`. 

Can you also check the duration (with mediainfo) from two clips where it stops between, and compare it with the duration in playlist?

**Comment by darshanvithani** [comment]
https://pastebin.com/raw/7kuUxBe2 .  in here there is a new view start on 10:00 but its hold for 4 minute and the restart . this is result of above video i sent

**Comment by darshanvithani** [comment]
> mediainfo

playout is giving correct sec here i cross cheak it

**Comment by darshanvithani** [comment]
How many threads i have to set in ffmpeg ?

**Comment by jb-alvarado** [comment]
I would not limit them, just let ffmpeg use what it needs.

Here is says:

```
[2019-08-16 09:24:51,454] [INFO]  open: /playlists/2019/08/2019-08-16.json
[2019-08-16 09:24:51,769] [INFO]  play: "/var/www/html/conveted_video/Amuary Specials/Specials - part 7.mp4"
[2019-08-16 09:24:53,810] [ERROR]  Playlist is only 23:32:44.413300 hours long!
[2019-08-16 09:38:10,374] [ERROR]  Sync tolerance value exceeded, program terminated!
[2019-08-16 09:38:10,374] [INFO]  got close command
```
This `Sync tolerance value exceeded, program terminated!` means that something is not right with timing, clip is shorter or longer the the durations from playlist.

**Comment by darshanvithani** [comment]
is there any setting on start with 00:00:00 ..or something .. because this work well before

**Comment by jb-alvarado** [comment]
There is only one setting for setting the starttime and that is `day_start` in config.

Until now I can not reproduce your problem. I thing something is wrong with the gui, or generating fron the playlists. I don't know which version was working for your, but in the last months I changed many things. But in our production everything runs smoothly. We only don't generate our playlists with ffplayout-gui.

**Comment by darshanvithani** [comment]
> There is only one setting for setting the starttime and that is `day_start` in config.
> 
> Until now I can not reproduce your problem. I thing something is wrong with the gui, or generating fron the playlists. I don't know which version was working for your, but in the last months I changed many things. But in our production everything runs smoothly. We only don't generate our playlists with ffplayout-gui.

i test much time and finally got something is 
1. if the video is in enough length 8 minutes or more and then it works fine with playout 
2. if i put some 15 to 51 or more sec video then it has an issue . that video is skipped and another video is started.
3. so between two video shot length video if put then it skips and then it time async and it applies in all other videos 
4. after that all video has good length but the problem that is playout stop and start

**Comment by darshanvithani** [comment]
> There is only one setting for setting the starttime and that is `day_start` in config.
> 
> Until now I can not reproduce your problem. I thing something is wrong with the gui, or generating fron the playlists. I don't know which version was working for your, but in the last months I changed many things. But in our production everything runs smoothly. We only don't generate our playlists with ffplayout-gui.


after lots of test and probality test . that problem occurs when i put logo . if not put then no problem .. if i put then its go black screen and then play sometime skip and then start to stop playlist

**Comment by jb-alvarado** [comment]
We need a way where I'm able to reproduce this, then I can say what is really happen and how to fix it. Maybe we collect some clips from internet, or create test clips with ffmpeg and create a scenario where this errors will come up. Maybe tomorrow I have time to make clips with different lengths and put them to a repo.

**Comment by jb-alvarado** [comment]
Ok, I have created a [repo](https://github.com/ffplayout/test-clips) with test clips and a playlist. 

The paths in playlist are relative, that means when you are with terminal in your ffplayout-engine repo folder and you start:
`./ffplayout.py -c ffplayout.conf -p ../test-clips/_playlist.json`
it should start correctly.

You could try this and see if there are errors coming.

Please make before a fresh pull from master and only change `preview = True` in config file from repo, or when you want to test rtmp you could run ffplay before starting ffplayout.py with:

`ffplay -listen 1 rtmp://127.0.0.1/live/stream`
