### ISSUE TITLE
RTMP Url is not play when in play-out 

### ISSUE THREAD

**Issue by darshanvithani** [ffplayout/ffplayout-engine#28]
it show  in log 

> Aug 18 10:07:11 s54689 systemd[1]: Stopping python and ffmpeg based playout...
> Aug 18 10:07:11 s54689 ffplayout.py[3086]: av_interleaved_write_frame(): Broken pipe
> Aug 18 10:07:11 s54689 systemd[1]: ffplayout.service: Main process exited, code=dumped, status=3/QUIT
> Aug 18 10:07:11 s54689 systemd[1]: Stopped python and ffmpeg based playout.
> Aug 18 10:07:11 s54689 systemd[1]: ffplayout.service: Unit entered failed state.
> Aug 18 10:07:11 s54689 systemd[1]: ffplayout.service: Failed with result 'core-dump'.
> Aug 18 10:07:11 s54689 systemd[1]: Started python and ffmpeg based playout.

**Comment by jb-alvarado** [comment]
Normally this is not related to ffplayout, maybe the receiver is not accepting the stream. When things like this is happen, try same settings and address with an normal ffmpeg instance.

**Comment by darshanvithani** [comment]
i have test with direct ffmpeg and it work but this is not work in our playout
