### ISSUE TITLE
apk add ffplayout

### ISSUE THREAD

**Issue by lavvy** [ffplayout/ffplayout-engine#31]
ffplayout is growing successfully as a portable cloud app service. It will be fine to add it to alpine repo as alpine is now being used mostly as base for docker containers in the cloud.

**Comment by jb-alvarado** [comment]
If somebody is willing to integrate this, he is very welcome :-) !

**Comment by 2bryvvpba81w** [comment]
jb-alvarado, sry for posting here, but any possible way to contact with you? you not answer at your email at pixelcrusher.

**Comment by jb-alvarado** [comment]
Hi, email is normally the best. At the moment I'm just to busy. Have you Nasser? When not, maybe I got not your mail.

**Comment by jb-alvarado** [comment]
@2bryvvpba81w please take a look at #33

**Comment by jb-alvarado** [comment]
If you still interested, there is now a dockerized version from ffplayout: https://github.com/ffplayout/ffplayout-docker
