### ISSUE TITLE
Logo show/hide

### ISSUE THREAD

**Issue by mustafalani** [ffplayout/ffplayout-engine#34]
Hi,

I'm working on RESTful API to modify ffplayout.conf and would like to be able to set a show/hide logo in the configuration file like:

[PRE_COMPRESS]
show_logo = True/False

Would it make sense?

The idea is to make a separate playlist config file for each playlist using RESTful API.

**Comment by jb-alvarado** [comment]
Hi,
yes I think I can do this. At the moment I'm on the dev branch, when this is done than I can integrate this feature.
