### ISSUE TITLE
Take next?

### ISSUE THREAD

**Issue by mustafalani** [ffplayout/ffplayout-engine#35]
Would it possible to implement a "take next" feature? i.e. drop the currently playing clip and play the next one now.

**Comment by jb-alvarado** [comment]
Theoretically this could work, but the result would be unpredictable. That means it could go 5 times well and destroy the stream at the 6th time. This would not guarantee stability, which is more important for me.

**Comment by mustafalani** [comment]
Could you try it? It is an essential feature in the playout automation.

**Comment by jb-alvarado** [comment]
You can try it for your self: https://github.com/jb-alvarado/test-scripts/blob/master/switcher.py
I have play with it some month ago and I was not satisfy. When you found a solid solution, we can think about how to integrate this. But then we have also to think about how to stay sync with time.

**Comment by mustafalani** [comment]
Thanks - I will give it a try.
