### ISSUE TITLE
Loop a clip and loop playlist

### ISSUE THREAD

**Issue by mustafalani** [ffplayout/ffplayout-engine#36]
Hi,

Can a clip in the playlist be looped for "n" times? also, can the playlist be looped?

I have the following list for example .. and I would like to loop the first clip 5 times and then loop the whole playlist over and over, can that be done?

```
{
    "channel": "Test 1",
    "date": "2019-08-20",
    "program": [
        {
            "begin": "0:00:00.000",
            "in": 0,
            "out": 15.162,
            "duration": 15.162,
            "source": "/home/ffplayout-engine/test-clips/Peru_00-00-15.mp4"
        },
        {
            "begin": "0:00:00.000",
            "in": 0,
            "out": 120.162,
            "duration": 120.162,
            "source": "/home/ffplayout-engine/test-clips/Orchid_00-02-00.mp4"
        }
    ]
}
```

What does this function really do? "# loop through all clips in playlist"

**Comment by jb-alvarado** [comment]
Hello!
> Can a clip in the playlist be looped for "n" times?

This will be supported in the next release. I'm working currently in dev branch, there it is integrated already, but at the moment the code is broken. I try to clean up some functions, and this takes time.

> also, can the playlist be looped?

This can be done by passing the playlist as argument (`-p playlist.json`)

> What does this function really do? "# loop through all clips in playlist"

this loop gets the correct clip in time.

**Comment by mustafalani** [comment]
> This can be done by passing the playlist as argument (-p playlist.json)

I'm doing this already - but the stream freezes on the last frame of the last clip

here is a sample playlist:
`{
    "channel": "Test 1",
    "date": "2019-08-20",
    "program": [
        {
            "begin": "0:00:00.000",
            "in": 0,
            "out": 15.162,
            "duration": 15.162,
            "source": "/home/ffplayout-engine/test-clips/Peru_00-00-15.mp4"
        },
        {
            "begin": "0:00:00.000",
            "in": 0,
            "out": 120.162,
            "duration": 120.162,
            "source": "/home/ffplayout-engine/test-clips/Orchid_00-02-00.mp4"
        }
    ]
}`

**Comment by mustafalani** [comment]
> This will be supported in the next release. I'm working currently in dev branch, there it is integrated already, but at the moment the code is broken. I try to clean up some functions, and this takes time.

since you are still working on this, would it be possible to add the number of times should the clip looped by passing `-stream_loop %number` in ffmpeg and also define that number in the playlist to look like this:
```
{
  "channel": "Test 1",
  "date": "2019-08-20",
  "program": [
    {
      "begin": "0:00:00.000",
      "duration": 15.162,
      "in": 0,
      "out": 15.162,
      "loop": 2,
      "source": "/home/iohub/ffplayout-engine/test-clips/Peru_00-00-15.mp4"
    },
    {
      "begin": "0:00:00.000",
      "duration": 120.162,
      "in": 0,
      "loop": 0,
      "source": "/home/iohub/ffplayout-engine/test-clips/Orchid_00-02-00.mp4"
    }
  ]
}
```
Cheers

**Comment by mustafalani** [comment]
> This will be supported in the next release. I'm working currently in dev branch, there it is integrated already, but at the moment the code is broken. I try to clean up some functions, and this takes time.

since you are still working on this, would it be possible to add the number of times should the clip looped by passing `-stream_loop %number` in ffmpeg and also define that number in the playlist to look like this:

```
{
  "channel": "Test 1",
  "date": "2019-08-20",
  "program": [
    {
      "begin": "0:00:00.000",
      "duration": 15.162,
      "in": 0,
      "out": 15.162,
      "loop": 2,
      "source": "/home/ffplayout-engine/test-clips/Peru_00-00-15.mp4"
    },
    {
      "begin": "0:00:00.000",
      "duration": 120.162,
      "in": 0,
      "loop": 0,
      "source": "/home/ffplayout-engine/test-clips/Orchid_00-02-00.mp4"
    }
  ]
}
```
Cheers

**Comment by jb-alvarado** [comment]
> since you are still working on this, would it be possible to add the number of times should the clip looped by passing `-stream_loop %number` in ffmpeg and also define that number in the playlist to look like this:

For the fact that I always need the `out:` value in playlist a loop key would be a bit redundant. I decided that the loop count will be calculated from `out`. When `out` is higher than `duration`, lets say:

```
duration: 20
out: 30
```
then the clip will loop two time, but cut after 30 seconds.


> > This can be done by passing the playlist as argument (-p playlist.json)
> 
> I'm doing this already - but the stream freezes on the last frame of the last clip
> 

Maybe because your playlist is not 24 hours long.That is not supported yet.

**Comment by mustafalani** [comment]
sorry for opening this ticket again

I tried what you suggested here
> then the clip will loop two time, but cut after 30 seconds.

but now I got a black stream after the last frame of "test3.mov"
here is my list:

```
{
      "begin": "0:00:00.000",
      "duration": 572.61,
      "in": 0,
      "out": 572.61,
      "source": "/movies/test1.mov"
    },
    {
      "begin": "0:00:00.000",
      "duration": 166.4,
      "in": 0,
      "out": 166.4,
      "source": "/movies/test2.mov"
    },
```
and here is my config

```
[GENERAL]
stop_on_error = True
stop_threshold = 11

[MAIL]
subject = "Playout Error"
smpt_server = mail.example.org
smpt_port = 587
sender_addr = ffplayout@example.org
sender_pass = 12345
recipient = 
mail_level = ERROR

[LOGGING]
log_to_file = True
log_file = ../playlists/logs/test-rundown-01_4j3b.log
log_level = INFO

[PRE_COMPRESS]
width = 1920
height = 1080
aspect = 1.778
fps = 25
logo = ../playlists/logos/test-rundown-01_4j3b.png
logo_opacity = 0.7
logo_filter = overlay=W-w-12:12
live_protocols = ["http", "https", "ftp", "rtmp", "rtmpe", "rtmps", "rtp", "rtsp", "srt", "tcp", "udp"]

[PLAYLIST]
playlist_mode = True
path = /playlists
day_start = 

[STORAGE]
path = /movies/
filler_path = /movies
filler_clip = /movies/big_buck_bunny.mov
extensions = ["*.mov"]
shuffle = False

[TEXT]
textfile = ../playlists/text/test-rundown-01_4j3b.txt
fontsize = 24
fontcolor = white
fontfile = /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
box = 1
boxcolor = black@0xbb
boxborderw = 6
x = w-w/8*mod(t,8*(w+tw)/w)
y = (h-line_h)*0.9

[OUT]
preview = False
service_name = Live Stream
service_provider = example.org
post_comp_video = ["-pix_fmt", "uyvy422"]
post_comp_audio = ["-ac", "2"]
post_comp_extra = ["-f", "libndi_newtek"]
out_addr = test-rundown-01_4j3b
```

**Comment by jb-alvarado** [comment]
Which version are you using? 

In general you don't need `"begin": "0:00:00.000",` any more. I know I had it in test repo, but it was for debugging only. Sorry. I remove it now.

Can you try last version from **dev** branch? And for the clips the ones from test repo?

My list looks like:

```
{
    "channel": "Test 1",
    "date": "2019-08-20",
    "program": [
        {
            "in": 0,
            "out": 15.162,
            "duration": 15.162,
            "source": "../test-clips/Peru_00-00-15.mp4"
        },
        {
            "in": 0,
            "out": 35.162,
            "duration": 15.162,
            "source": "../test-clips/SandyBrown_00-00-15.mp4"
        },
        {
            "in": 0,
            "out": 3.162,
            "duration": 3.162,
            "source": "../test-clips/SlateGray_00-00-03.mp4"
        }
    ]
}

```

And my start command:

```
./ffplayout.py -p ../test-clips/_playlist2.json -s now -t none -d
```

**Comment by mustafalani** [comment]
I checked the dev branch and both loops (loop a clip and loop a list) are working, but I realized if I use `--loop ` for an infinite loop - then the playlist isn't dynamic anymore, is that how it acts if the list is looped?

**Comment by jb-alvarado** [comment]
Have you try to edit the palylist and save it? Because it will only reload when there is a change.

**Comment by mustafalani** [comment]
Yes - whenever I change the list I save it. I have been testing the dev branch the whole day - it seems like when `--loop` is passed, the changes sometimes take place and sometimes don't.

**Comment by jb-alvarado** [comment]
And do you see the same effect to, when you don't use `--loop` and you edit the list? Because both should use the functionality. Until know I could not reproduce it.
