### ISSUE TITLE
Broken pipe in v1.7.1

### ISSUE THREAD

**Issue by tg8kuyx3kygbusyf** [ffplayout/ffplayout-engine#37]
After playing first video in folder mode, stream stops with error: https://gist.github.com/tg8kuyx3kygbusyf/61314f9ead26213f1e4589a46e92ed55

In v1.6.1 all work fine.

**Comment by jb-alvarado** [comment]
Thank you for reporting! I have try to reproduce, but by me it works normal. Which ffmpeg version do you use?

**Comment by tg8kuyx3kygbusyf** [comment]
I use at ArchLinux with ffmpeg 4.2.1
Any possible way to help you debug this? log_level = DEBUG looks not so helpful.

**Comment by jb-alvarado** [comment]
You could try the `dev` branch. This has a better logging from ffmpeg pre process.

**Comment by jb-alvarado** [comment]
Is there still any problem? When not I will close this issue...

**Comment by jb-alvarado** [comment]
This issue is similar to #42, and should be fixed with 5f45645
