### ISSUE TITLE
program stats and logging

### ISSUE THREAD

**Issue by mustafalani** [ffplayout/ffplayout-engine#38]
Hi,

I know that ffplayout is logging to a file which can even be set in the playlist conf or passed in the command line, but that log doesn't tell much about the progress of the currently running file and what is next.

Do you have any idea how to track the playlist and see its progress? for example, I would like to see (now playing, next playing, now playing progress, playlist progress).

**Comment by jb-alvarado** [comment]
Hi,
in general [ffplayout-gui](https://github.com/ffplayout/ffplayout-gui) was made for this. I think it still work, but looks ugly and is not good maintained. My dream is to completely rewrite it, but at the moment I don't know how to get the time for it. I think with python pyside2 or pyQT it would not that much difficult to write something what can do this, but I don't have the capacity for that too. ffplayout was also made more for the cloud and there your don't have a GUI.

In my work we use the ffplayout-gui with an open source php login framework. And for the TV we convert the playlist to an mysql database. But this things everybody have to do for him self. I think some work cases are very specific, so is hard to make something general what everybody can use. For example we have an religious internet tv station, so our playlist; categories; ads and so on a totally different to a normal tv station. It would be hard to have a system what everybody can use.

In general my advise would be, to separate both things. The playout and the tracking of the playlist. The new version will have a bit more logging, but more for debugging purposes. To log even the progress could produce to much overhead and maybe instability.

**Comment by mustafalani** [comment]
How do you see the progress in ffplayout-gui? are you reading from stdout? I'm also doing something similar to what you do in your work and have written a ffplayout-api , but yet there are many features missing- I have so far ported - read ffplayout config file, create playlist config, update playlist config, add/remove/update playlist items, set loop to items and playlist, start/stop playlist.

**Comment by jb-alvarado** [comment]
No it reads with php the json playlist and with js it makes the calculation.

In the future I plan a little API to, but mostly for sending text to overlay.

**Comment by mustafalani** [comment]
got you - the problem with tracking the list by only reading the json file is that you never know which clip is currently running if the clip is repeated in the list.

What I was thinking of is to add a "`clip_id`" in the playlist like:
```
{
  "channel": "channel-01",
  "date": "2019-11-09",
  "program": [
    {
      "begin": "0:00:00.000",
      "duration": 166.4,
      "id": 1,
      "in": 0,
      "out": 332.8,
      "source": "/clip1.mov"
    },
    {
      "begin": "0:00:00.000",
      "duration": 138.29,
      "id": 2,
      "in": 0,
      "out": 138.29,
      "source": "/clip2.mov"
    },
    {
      "begin": "0:00:00.000",
      "duration": 572.61,
      "id": 3,
      "in": 0,
      "out": 572.61,
      "source": "/clip3.mov"
    }
  ]
}
```
then log something like:
```
[2019-11-14 11:47:57,064] [INFO]  Play: "/clip.mov", id: 001
```
 that way - it will be possbile to watch the messages and get the start time of each clip and its position in the list.

**Comment by jb-alvarado** [comment]
Normally the start time is know, with that and `out` and `seek` you can always calculate the current clip. That is what the GUI does and also the engine. But I belief there is may other ways to calculate this. The json playlist format is very open, so you can add as many keys and values you want. The engine just picks what it needs.

**Comment by jb-alvarado** [comment]
The engine tracks also the [index](https://github.com/ffplayout/ffplayout-engine/blob/7718b56712dcf00329bd7f55e63ad8b746b7a88a/ffplayout.py#L1524). If you want you could log this to, it would be the same than the id.

**Comment by jb-alvarado** [comment]
I close here. You can open it again, if there is any questions.
