### ISSUE TITLE
Broken Pipe in shuffle folder mode

### ISSUE THREAD

**Issue by jb-alvarado** [ffplayout/ffplayout-engine#42]
Well, not all fixed.
Its works perfect all night, but when i set "shuffle folder mode" i get:
```
[2019-12-01 12:04:48,894][ERROR]    [encoder] av_interleaved_write_frame(): Broken pipe
[2019-12-01 12:04:49,003][ERROR]    [encoder]     Last message repeated 1 times
[2019-12-01 12:04:49,003][ERROR]    [encoder] Error writing trailer of rtmp://*: Broken pipe
[2019-12-01 12:04:49,015][ERROR]    [decoder] av_interleaved_write_frame(): Broken pipe
[2019-12-01 12:04:49,055][ERROR]    Broken Pipe!
```
Need more time to debug this...
Also, what system are you using?

_Originally posted by @tg8kuyx3kygbusyf in https://github.com/ffplayout/ffplayout-engine/pull/41#issuecomment-560081552_

**Comment by jb-alvarado** [comment]
Tomorrow I will setup an testing environment for that. Can you post me also the log line before:

```
av_interleaved_write_frame(): Broken pipe
```
Here it only say that the decoding process before is broken. But we need to know why.

For developing I use mostly fedora 31, before it was Windows and macOS. For testing and production I use debian 10. On all platforms I have an self compiled ffmpeg version.

**Comment by tg8kuyx3kygbusyf** [comment]
Well, all works fine in "folder" mode only when i don't use logo :)
If i use logo, only first file plays, then stream stops with error "Broken Pipe!".

**Comment by tg8kuyx3kygbusyf** [comment]
With default logo fails too.
Logs [here.](https://a.uguu.se/77A2GMcOyd18.xz)

**Comment by jb-alvarado** [comment]
I'm still on testing, strangely I can't reproduce it at the moment. Can you try it with the [test clips](https://github.com/ffplayout/test-clips)?

**Comment by jb-alvarado** [comment]
Ok, now in my testing environment I have the same problem. I have here also way more video clips. I could imaging that the problem is the shuffle function, maybe it is to slow. I will try something and put it in dev branch.

**Comment by jb-alvarado** [comment]
Maybe I have it, can you try the dev branch? I think the problem was the combination from frame rate change and the logo. But let's see how it work by you.

**Comment by tg8kuyx3kygbusyf** [comment]
Sorry for late answer, in 1.8.5 all works just fine.
Thank you!
