### ISSUE TITLE
Customization requests

### ISSUE THREAD

**Issue by ilimaan** [ffplayout/ffplayout-engine#44]
Hello there,
I'm interested in hiring you for a customization.

If you're interested please, get back to me by Skype: a-art.pdg?

**Comment by jb-alvarado** [comment]
Hello, can you please send me an email first, with the customization you need?
So I can think first if it is possible and how long I would need.

Have a good day!

**Comment by ilimaan** [comment]
What is your email address?
Mine is ilimaan (@) acan.email

Remove the spaces and ().

**Comment by jb-alvarado** [comment]
Ok, I wrote to you.
