### ISSUE TITLE
Multiple channels

### ISSUE THREAD

**Issue by casic** [ffplayout/ffplayout-engine#49]
Hi, 
Can it play more then one channel ??

**Comment by jb-alvarado** [comment]
Hello, 
I have not test it, but I think it should be possible. You just need multiple systemd services, and in all you adjust this line:

```
ExecStart=/opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py -c /etc/ffpalyout/ffplayout-1.yml
```
And in every service you pass a different config file.

The downside is, that the GUI will not support this at the moment. But I'm working on a new one, and I can think about it, to put it on my TODO.

**Comment by casic** [comment]
Thanks, i will try . But  start to make  admin web panel to make play
list , add channel   so on.   Is it possible  config for every channel to
be  get with url  ?

На пт, 17.04.2020 г. в 20:36 jb-alvarado <notifications@github.com> написа:

**Comment by jb-alvarado** [comment]
I'm not sure if I understand you correctly. You want now manage multiple channels with the web GUI

That is not possible with the current version. You could use different subdomains, for every channel, or aliases. And have different web roots, and for every one you can use a different config. That is the only way I think it works at the moment.

**Comment by jb-alvarado** [comment]
In dev branch I'm working now on multi channel support. For that I switch to supervisord, because we can easily add new instances to [conf.d](https://github.com/ffplayout/ffplayout-engine/tree/dev/supervisor/conf.d). Every instance get its own engine config and that's it already.

**Comment by jb-alvarado** [comment]
Done in master branch.
