### ISSUE TITLE
Playlist length configuration format

### ISSUE THREAD

**Issue by pkExec** [ffplayout/ffplayout-engine#50]
[This ](https://github.com/ffplayout/ffplayout-engine/wiki/The-Configuration-File)implies that the playlist length configuration is in "HH:mm:ss" format.

[This ](https://github.com/ffplayout/ffplayout-engine/blob/b45df954a49204f129489d4c2d7f3dd73b956420/ffplayout/playlist.py#L47)seems to suggest that the playlist length is in total seconds format.

Which is correct?

**Comment by jb-alvarado** [comment]
**HH:mm:ss** is the correct format. The script [converts](https://github.com/ffplayout/ffplayout-engine/blob/b45df954a49204f129489d4c2d7f3dd73b956420/ffplayout/utils.py#L126) the value to seconds.
