### ISSUE TITLE
drawtext from filename

### ISSUE THREAD

**Issue by nativemad** [ffplayout/ffplayout-engine#52]
I use ffplayout-engine with a piped output to tvheadend.
This is working very well in random mode on a folder with music videos.
In fact, so well that my friends just don't stop adding great tunes to the library.
The only problem with that is that everyone needs to use shaz* app to find out what they are listening to right now.

I played a bit with drawtext on the complex_filters, but my ffmpeg as well as python skills are just too bad to get it right.

Would it be possible to implement yet another drawtext api, but to the encoder and get some config options for settings like those below?
-when to put the text (after one minute for example)
-duration while the text should be displayed (for one minute)
-a regex/str-replace to filter yt-id's and file extensions from the filenames and such
-font, -size, -color, -position to distinguish the text apis 

I thought about adding that through the existing text api, but an extra wrapper that looks after ffmpeg processes is quite a messy solution i guess.

Thank you already for the great work!

**Comment by jb-alvarado** [comment]
Technically it is possible, but I would like to have it more generic. Maybe a solution where different filters can be apply. We can think more about it and see if it is possible.

But it will take time, because at the moment the priorities are more on the GUI.

**Comment by jb-alvarado** [comment]
In master branch there is now support for that.

**Comment by nativemad** [comment]
Awesome! Thank you, it is working as expected! :-)
