### ISSUE TITLE
Question about loop

### ISSUE THREAD

**Issue by HolgerHuo** [ffplayout/ffplayout-engine#57]
Hi, I have read a few documentation and issues to try to figure out the function **loop**, but I'm still a bit confused.(sorry for my poor comprehension)

You have mentioned that a playlist with play 24/7 if the duration is set to 24 hours but shouldn't that mean the playlist will only play for 24 hours or should I use the crontab to continue playing? 

Thank for your developing ❤️.

**Comment by HolgerHuo** [comment]
BTW,can storage mode be used for looping? According to the documentation,only the filler clip will be used for looping. Can I loop the complete folder, and for more than 24h?

**Comment by jb-alvarado** [comment]
Hi,
I mean with that, that normally you have for every day a playlist, let's say:
```
/playlist/2020/07/2020-07-01.json
/playlist/2020/07/2020-07-02.json
/playlist/2020/07/2020-07-03.json
/playlist/2020/07/2020-07-04.json
...
```
every playlist should have content for 24 hours.

When you setup up now your config: **playlist -> day_start** to your desirable time and **playlist -> length** to **24:00:00**, ffplayout will run endless (as long it gets always a new playlist). It will grab for every day a new playlist. For this use case 
is also the systemd service.

This scenario work only if playlists are 24 hours long. When you want to have, for example, only 10 hours long playlist, and playing them from 00:00 to 10:00 o clock, it will not work automatically, for that you need a cronjob.

A third scenario is, when you pass a playlist as argument to ffplayout:

```
./ffplayout.py -p playlist.json
```
 In this case, ffplayout will loop the playlist endless.

To your seconds post: yes in folder mode, it plays also endless and will continue looping the folder.

**Comment by HolgerHuo** [comment]
I see that. Thanks a lot!
One more thing: what is filler clip used for?
> To reach 24h

As you have said. 
Thanks for your help!

**Comment by jb-alvarado** [comment]
> I see that. Thanks a lot!
Your are welcome!

> One more thing: what is filler clip used for?

Let's say your playlist is 23:30 hours long, instead of 24:00 hours. Then ffplayout will use this filler clip to fill the last 30 minutes. If this clip does not exist you will get a black clip with noise in audio. Ideally this filler clip is loopable so it have smooth transitions.

**Comment by HolgerHuo** [comment]
got it
Thanks a lot~
