### ISSUE TITLE
pipe out

### ISSUE THREAD

**Issue by wturra** [ffplayout/ffplayout-engine#58]
Hi, could you tell me how to pipe out ? I tried pipe out using stream and hls but always with error.

Regards.

**Comment by jb-alvarado** [comment]
Can you provide a test setting, maybe in shell how you would like to have this pipe? Normally it should work, but of course there must  be a program open first, which uses the pipe.

**Comment by jb-alvarado** [comment]
Now it come's to my mind... It is not so easy, because python is not forwarding the pipe to stdout. For this use case you have to write your own [output module](https://github.com/ffplayout/ffplayout-engine/wiki/Outputs).

**Comment by nativemad** [comment]
Don't know if this is still a question, but for the record, I use "-f mpegts pipe:1" within the stream_output section to stream to stdout and pipe it to tvheadend. ;-)
