### ISSUE TITLE
Maximum possible video quality

### ISSUE THREAD

**Issue by application-programming-interface** [ffplayout/ffplayout-engine#60]
Hi!
I set maximum video quality trough ffplayout.yml, but its looks ugly at some point (especialy at dark parts of video or when there is a lot of movement).
Any special configs or some advice?
Sry for asking here, i wrote you an email, but you dont answer.. 😶

**Comment by jb-alvarado** [comment]
Hi, can you post your output part from config file, and your target resolution.

**Comment by application-programming-interface** [comment]
1280x720
-crf 1
-maxrate 10000k
-bufsize 10000k
-profile:v high
-preset ultrafast

**Comment by jb-alvarado** [comment]
I made a little update where I calculate the preprocessing rate different. You could try this commit, but is better to check it with desktop mode. When the picture in desktop mode looks good, something with your output is not correct. **crf** I would not set under 17, and when you use so low numbers, I think maxrate is not enough. Another question is to, if your rtmp server is also recompressing the stream.

**Comment by application-programming-interface** [comment]
Okay, i try it.
>Another question is to, if your rtmp server is also recompressing the stream.
Nope.
