### ISSUE TITLE
Questions about hardware and OS

### ISSUE THREAD

**Issue by cdavid14** [ffplayout/ffplayout-engine#64]
Hello Everyone,

i'm trying having references about where you guys are using the ffplayout as the hardware that you use and the OS that you're running (production or development), can you guys help-me with this? I thank your help

**Comment by jb-alvarado** [comment]
Hello,

in production we running ffplayout on a self hosted debian 10 VM. The VM has 6 threads and 6 GB ram. In the VM runs also a srs server for rtmp and multi bitrate HLS.

In development I run ffplayout on fedora 32.
