### ISSUE TITLE
Watchdog not observing folder

### ISSUE THREAD

**Issue by Sommerzeit** [ffplayout/ffplayout-engine#69]
**Describe the bug**
Watchdog is not watching the folder, because the patterns are not formed well.

**Expected behavior**
Watchdog notices changes in the observed folder

I'm not fit enough in python to confidently commit a fix, but I helped myself with this:

```python
    def __init__(self, media):
        
        self._media = media
        
        self.patterns = []
        for ext in _storage.extensions:
            self.patterns.extend('*' + ext)
        
        self.event_handler = PatternMatchingEventHandler(patterns=self.patterns)
        self.event_handler.on_created = self.on_created
        self.event_handler.on_moved = self.on_moved
        self.event_handler.on_deleted = self.on_deleted

        self.observer = Observer()
        self.observer.schedule(self.event_handler, self._media.folder,
                               recursive=True)

        self.observer.start()
```

**Comment by Sommerzeit** [comment]
It would also be marvelous if the MediaWatcher class could monitor whether the currently playing file is being move or deleted. Then it could automatically play the next file.

**Comment by jb-alvarado** [comment]
Thank you, for the report! I also integrate the suggestion, but when it jumps to the next clip it is a bit un-smooth.
