### ISSUE TITLE
Enable environmental variables in the yaml config

### ISSUE THREAD

**Issue by Sommerzeit** [ffplayout/ffplayout-engine#70]
**Is your feature request related to a problem? Please describe.**
I need to start several instances of ffplayout, which mainly only differentiate in the folder they should read from (which can already be modified via command line arguments) and the target rtmp stream (which has to be in the yaml config file). It would be wonderfull if I could simply put ffplayout in a docker container (or a small vserver) and just pass parts of the config as environmental variables.

**Describe the solution you'd like**
Enable environmental variables in the yaml config file. This looks like a nice library to implement: [envyaml](https://pypi.org/project/envyaml)

**Describe alternatives you've considered**
More command line arguments, e.g. for the stream output

**Comment by jb-alvarado** [comment]
In later version I will integrate a multichannel support in the GUI, for that is better to have separate config file per Channel. When you want to run the engine in a container, you can easily mount different configs per container.

**Comment by stemcc** [comment]
> In later version I will integrate a multichannel support in the GUI, for that is better to have separate config file per Channel. When you want to run the engine in a container, you can easily mount different configs per container.

This sounds great. Do you have a timeline for when this version might be ready for testing?

**Comment by jb-alvarado** [comment]
At the moment I'm not able to get time for it, so I think it will take some months. It should not be to much work, so hopefully I can do it still in this winter.

**Comment by jb-alvarado** [comment]
Done in master branch
