### ISSUE TITLE
feature request: JSON-RPC2.0 

### ISSUE THREAD

**Issue by Fr6jDJF** [ffplayout/ffplayout-engine#75]
**Is your feature request related to a problem? Please describe.**
I would like to obtain some info about the current stream for another service/machine(involving the viewers chat), this by a simple json response from ffplayout. 
Something like [json-rpc](https://github.com/pavlov99/json-rpc) would allow this.

 
**Describe the solution you'd like**
A json-rpc implementation to Get and maybe Set some basic ffplayout status.

- get_now_playing(channel) # return item dict *example:
``` 
    "channel": "Test 1",
    "date": "2020-10-15",
    "sources_remaining": 37,
    "time_left_from_now_playing": 35070.080",
    "now_playing": [
      {
        "in": 0.0,
        "out": 3716.8,
        "duration": 3716.8,
        "category": "catogory1",
        "source_file_sha1": "4D9D8B8EB1715C57C6F939B685A18B6982A5B71A" # from json playlist?***
        "source_file_name": "S01E02.mp4" #lame filename, expecting duplicates
       or
        "source_file_ffmetadata":  {
                                   "title" : "Show - S01E02 Title"
                                   } # from json playlist?  ffmpeg -f -ffmetadata** 
      }
``` 
**[ffmpeg  -metadata](https://ffmpeg.org/ffmpeg-all.html#Example-1) / [FFmpeg_Metadata](https://wiki.multimedia.cx/index.php?title=FFmpeg_Metadata)
    `ffmpeg -i in.mp4 -metadata title='Show - S01E02 Title' -y -r 1 -acodec copy -vcodec copy cp.mp4`
    `ffmpeg -i cp.mp4 -f ffmetadata cp.txt`
```
;FFMETADATA1
major_brand=isom
minor_version=512
compatible_brands=isomiso2avc1mp41
title=Show - S01E02 Title
encoder=Lavf58.53.100
```

***sha1 time 98MB/SSD
```
print (timeit.repeat(
"""
import hashlib
filename = 'test_vid.mp4' #98MB
with open(filename,"rb") as f:
    bytes = f.read() # read file as bytes
    #h = hashlib.md5(bytes).hexdigest() # [0.14477800100030436]
    h = hashlib.sha1(bytes).hexdigest() # [0.07417453400012164]
    #h = hashlib.sha256(bytes).hexdigest() # [0.07694024000011268]
    #h = hashlib.sha512(bytes).hexdigest() # [0.13460509499964246]
    #h = hashlib.blake2b(bytes).hexdigest() # [0.14861350099999981]
    #h = hashlib.blake2s(bytes).hexdigest() # [0.21141092399921035]
""",
repeat=1, number=1))
```

- get_playlist_next_up(channel, amount=2): # return items dict example:
``` 
    "channel": "Test 1",
    "date": "2020-10-15",
    "sources_remaining": 37,
    "time_left_from_now_playing": 35070.080",
    "program_chunk": [
      {
        "......."
      },
      {
        "......."
      },
    "result_amount": 2, 
``` 
- get_playlist_by_scope(channel, time_in=init_time, time_out=total_playtime): # return items dict example:
``` 
    "channel": "Test 1",
    "date": "2020-10-15",
    "sources_remaining": 37,
    "time_left_from_now_playing": 35070.080",
    "program_chunk": [
      {
      {
        "......."
      },
      {
        "......."
      },
    "result_scope":  {"from": "<time_in>", "up_to" : <time_out>"},
```
Further interesting options:
   - set_rtmp(channel, url) https://github.com/ffplayout/ffplayout-engine/issues/65 # return status str
   - set_messenger(channel, **) https://github.com/ffplayout/ffplayout-engine/issues/52 # return status str
   - ...

*for my use case, serving such dict offers info to allow users to generate video (offset in/out based) clips from video by chat commands. cutting out weak/boring parts of certain category video's, to improve upcoming playlist.
As for the sha1 value, I have written in bash some rough concept of a `yyyy-mm-dd.json` playlist generator based on recipe(time budget category x,y,z for day_part mo,af,ev, by min/max length day_part mo,af,ev, and lowest "been added" count, with file order mix or asc.(user tune-able prepared playlist, which makes the job optional, not desired to get flavoured mixed content across the day).
I would like to rewrite that in Python+Sqlite (and use such sha1 from file to keep track of it, so ffplayout metadata from playlist and .db can be paired again with file, when a file has been moved), 
where I also want to generate fillers before outputting `yyyy-mm-dd.json`, to fill up day-parts(or being recipe value) by something like /`mediaStorage/20201212/nextup_0001.mp4`, daily rendered for the next day playlist.

**Describe alternatives you've considered**
Combine data from:
Scraped ffplayout.log for now playing info
+
request info from /viewers at ffplayout rtmp destination(nginx) to get playing/publishing status

**Additional context**
From a little test I did with [json-rpc](https://github.com/pavlov99/json-rpc) and ffplayout.log scraping
_Monitor service:_
```python
from werkzeug.wrappers import Request, Response
from werkzeug.serving import run_simple

from jsonrpc import JSONRPCResponseManager, dispatcher
from enum import Enum


class StreamState(Enum):
    offline = 0
    changed = 1
    unchanged = 2

class Ffp():
    def __init__(self, logfile):
        self.logfile = logfile
        
    def ffp_log(self):
        # Removed Scraping Part, 
        # Removed Filename Resolving/Sanitizing Part *alias.db
        # Removed nginx /viewers Part
        return StreamState.changed, 'playing something..'

@dispatcher.add_method
def now_broadcasting(**kwargs):
    status, data = f.ffp_log()
    if status == StreamState.offline :
        return f'rtmp {kwargs["stream"]} offline'
    elif status == StreamState.changed:
        return data
    elif status == StreamState.unchanged:
        return data
    return 'error'

@Request.application
def application(request):
    # Dispatcher is dictionary {<method_name>: callable}
    response = JSONRPCResponseManager.handle(
        request.get_data(cache=False, as_text=True), dispatcher)
    return Response(response.json, mimetype='application/json')

if __name__ == '__main__':
    f = Ffp('/ffplayout.log')
    run_simple('localhost', 4000, application)
```
_Polling Client:_
```python
import requests
import json

url = "http://localhost:4000/jsonrpc"
headers = {'content-type': 'application/json'}

# Example now_broadcasting method
payload = {
    "method": "now_broadcasting",
    "params": {"stream": "key"},
    "jsonrpc": "2.0",
    "id": 3,
}
response = requests.post(
    url, data=json.dumps(payload), headers=headers).json()

assert response["result"]
assert response["jsonrpc"] == "2.0"
assert response["id"] == 3

print(response)
```

**Comment by jb-alvarado** [comment]
Hi, I can do it on my Todo, but I can not guarantee that in the next weeks I have the time for it.
Can you specify more, which infos you would like to expose?

**Comment by jb-alvarado** [comment]
At the moment I'm thinking about, what makes sense to integrate directly in **ffplayout-engine** and for what is better to use the [API](https://github.com/ffplayout/ffplayout-api/).

Setters I don't want to integrate in the engine. The API have already this options, so that would be redundant. A little bit the same is some of the getters, which get information from the playlist. This would have a better place in the API to. 

Getting information from the current clip can make sense, because it can usefull for others thing to, like for https://github.com/ffplayout/ffplayout-engine/issues/52 and in general, when a playlist has no start time, or when the engine runs in folder mode.
