### ISSUE TITLE
make get error

### ISSUE THREAD

**Issue by hishamalislam** [ffplayout/ffplayout-engine#76]
When try make get error.

# cd ffplayout-engine
# make
:~/ffplayout-engine# make
virtualenv -p python3 venv
/bin/bash: virtualenv: command not found
Makefile:5: recipe for target 'init' failed
make: *** [init] Error 127
![aa2](https://user-images.githubusercontent.com/75373935/100877521-1a5d5480-34d3-11eb-9dd9-5386876d77f9.JPG)

**Comment by jb-alvarado** [comment]
You need to install **virtualenv** first.
