### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by Marco-LB** [ffplayout/ffplayout-engine#78]
Hi I have a proxmox Ve system and I tried to install ffplayout inside a container (proxmox CT) with debian 10, the installation is successful but when I go to the ip address of the container I only see the default screen of nginx, where am I wrong?
Thanks in advance

**Comment by jb-alvarado** [comment]
Hi,
can it be, that there is still the default config under **/etc/nginx/site-enabled**?

**Comment by Marco-LB** [comment]
Hi i i delete default file on  /etc/nginx/site-enabled the sistem give me this error: ERR_CONNECTION_REFUSED

**Comment by jb-alvarado** [comment]
Have you restart the nginx service?

**Comment by Marco-LB** [comment]
yes but it doesn't work :-(
i try to use debian 9

**Comment by jb-alvarado** [comment]
Debian 10 is totally fine. Did you use the [install](https://github.com/ffplayout/ffplayout-frontend/blob/master/install.sh) script? When you did a manual installation, have you install the [API](https://github.com/ffplayout/ffplayout-api/blob/master/docs/install.md) to?
