### ISSUE TITLE
SDI video using decklink

### ISSUE THREAD

**Issue by sfahadshahzad** [ffplayout/ffplayout-engine#80]
Hi, 

Can I get video out on Decklink SDI. 

Regards, 

Fahad

**Comment by jb-alvarado** [comment]
Hi, yes sure - when your ffmpeg is compiled with decklink support you can use [stream_output](https://github.com/ffplayout/ffplayout-engine/blob/0c17342bc94416771b992115d8114ac85a89c562/ffplayout.yml#L126) for your SDI output settings.
