### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout-engine#82]
This is not really an issue but a question...

Some of my videos have black edges on top and bottom and some dont

https://prnt.sc/wzwruo

is there a ffmpeg command to make video fill the screen ?
Thanks for your help.

**Comment by jb-alvarado** [comment]
Yes ffmpeg can crop videos, but ffplayout can not crop some videos and others not. I made ffplayout in a way that it formats all videos to the same aspect ratio, that means that some videos with a wrong aspect gets borders. But normally that is not a problem, even when you crop the video and the aspect is different to the screen, you would get boards in full screen mode.

**Comment by jb-alvarado** [comment]
This can be done now by a [custom filter](https://github.com/ffplayout/ffplayout-engine/tree/master/ffplayout/filters). For that you have to extend your playlist program node, and write your crop information there. This info you can grab in your filter.

You only have to take care of the video aspect, this can not differ to the settings from your config.
